// Block type definitions

export enum BlockType {
  AIR = 0,
  GRASS = 1,
  DIRT = 2,
  STONE = 3,
  WOOD = 4,
  LEAVES = 5,
  SAND = 6,
  WATER = 7,
  COBBLESTONE = 8,
  PLANKS = 9,
  METAL = 10,
  OBSIDIAN = 11,
  PORTAL = 12,
  TELEPORTER = 13,
  DEEPSLATE = 14,
  TUFF = 15,
  RED_WOOL = 16,
  DARK_OAK = 17,
  SNOW = 18,
  ORANGE_GLASS = 19,
  DRIPSTONE = 20,
  BLACK_GLASS = 21,
  MAGMA = 22,
  ANDESITE_BLOCK = 23,
  BRICK = 24,
  HARDENED_CLAY_BLACK = 25,
  HARDENED_CLAY_CYAN = 26,
  HARDENED_CLAY_MAGENTA = 27,
  HARDENED_CLAY_ORANGE = 28,
  PAINTING_1 = 29,
  PAINTING_2 = 30,
}

export interface BlockDefinition {
  id: BlockType;
  name: string;
  solid: boolean;
  transparent: boolean;
  // Texture indices for each face [top, bottom, front, back, left, right]
  // Using single index means same texture for all faces
  textureIndex: number | [number, number, number, number, number, number];
}

export const BLOCK_DEFINITIONS: Record<BlockType, BlockDefinition> = {
  [BlockType.AIR]: {
    id: BlockType.AIR,
    name: 'Air',
    solid: false,
    transparent: true,
    textureIndex: 0,
  },
  [BlockType.GRASS]: {
    id: BlockType.GRASS,
    name: 'Grass',
    solid: true,
    transparent: false,
    textureIndex: [0, 2, 1, 1, 1, 1], // top=grass, bottom=dirt, sides=grass_side
  },
  [BlockType.DIRT]: {
    id: BlockType.DIRT,
    name: 'Dirt',
    solid: true,
    transparent: false,
    textureIndex: 2,
  },
  [BlockType.STONE]: {
    id: BlockType.STONE,
    name: 'Stone',
    solid: true,
    transparent: false,
    textureIndex: 3,
  },
  [BlockType.WOOD]: {
    id: BlockType.WOOD,
    name: 'Wood',
    solid: true,
    transparent: false,
    textureIndex: [5, 5, 4, 4, 4, 4], // top/bottom=log_top, sides=log_side
  },
  [BlockType.LEAVES]: {
    id: BlockType.LEAVES,
    name: 'Leaves',
    solid: true,
    transparent: true,
    textureIndex: 6,
  },
  [BlockType.SAND]: {
    id: BlockType.SAND,
    name: 'Sand',
    solid: true,
    transparent: false,
    textureIndex: 7,
  },
  [BlockType.WATER]: {
    id: BlockType.WATER,
    name: 'Water',
    solid: false,
    transparent: true,
    textureIndex: 8,
  },
  [BlockType.COBBLESTONE]: {
    id: BlockType.COBBLESTONE,
    name: 'Cobblestone',
    solid: true,
    transparent: false,
    textureIndex: 9,
  },
  [BlockType.PLANKS]: {
    id: BlockType.PLANKS,
    name: 'Planks',
    solid: true,
    transparent: false,
    textureIndex: 10,
  },
  [BlockType.METAL]: {
    id: BlockType.METAL,
    name: 'Metal',
    solid: true,
    transparent: false,
    textureIndex: 11,
  },
  [BlockType.OBSIDIAN]: {
    id: BlockType.OBSIDIAN,
    name: 'Obsidian',
    solid: true,
    transparent: false,
    textureIndex: 12,
  },
  [BlockType.PORTAL]: {
    id: BlockType.PORTAL,
    name: 'Portal',
    solid: false,
    transparent: true,
    textureIndex: 13,
  },
  [BlockType.TELEPORTER]: {
    id: BlockType.TELEPORTER,
    name: 'Teleporter',
    solid: true,
    transparent: false,
    textureIndex: 14,
  },
  [BlockType.DEEPSLATE]: {
    id: BlockType.DEEPSLATE,
    name: 'Deepslate',
    solid: true,
    transparent: false,
    textureIndex: 15,
  },
  [BlockType.TUFF]: {
    id: BlockType.TUFF,
    name: 'Tuff',
    solid: true,
    transparent: false,
    textureIndex: 16,
  },
  [BlockType.RED_WOOL]: {
    id: BlockType.RED_WOOL,
    name: 'Red Wool',
    solid: true,
    transparent: false,
    textureIndex: 17,
  },
  [BlockType.DARK_OAK]: {
    id: BlockType.DARK_OAK,
    name: 'Dark Oak',
    solid: true,
    transparent: false,
    textureIndex: 18,
  },
  [BlockType.SNOW]: {
    id: BlockType.SNOW,
    name: 'Snow',
    solid: true,
    transparent: false,
    textureIndex: 19,
  },
  [BlockType.ORANGE_GLASS]: {
    id: BlockType.ORANGE_GLASS,
    name: 'Orange Glass',
    solid: true,
    transparent: false,
    textureIndex: 20,
  },
  [BlockType.DRIPSTONE]: {
    id: BlockType.DRIPSTONE,
    name: 'Dripstone',
    solid: true,
    transparent: false,
    textureIndex: 21,
  },
  [BlockType.BLACK_GLASS]: {
    id: BlockType.BLACK_GLASS,
    name: 'Black Glass',
    solid: true,
    transparent: false,
    textureIndex: 22,
  },
  [BlockType.MAGMA]: {
    id: BlockType.MAGMA,
    name: 'Magma',
    solid: true,
    transparent: false,
    textureIndex: 23,
  },
  [BlockType.ANDESITE_BLOCK]: {
    id: BlockType.ANDESITE_BLOCK,
    name: 'Andesite',
    solid: true,
    transparent: false,
    textureIndex: 24,
  },
  [BlockType.BRICK]: {
    id: BlockType.BRICK,
    name: 'Brick',
    solid: true,
    transparent: false,
    textureIndex: 25,
  },
  [BlockType.HARDENED_CLAY_BLACK]: {
    id: BlockType.HARDENED_CLAY_BLACK,
    name: 'Black Clay',
    solid: true,
    transparent: false,
    textureIndex: 26,
  },
  [BlockType.HARDENED_CLAY_CYAN]: {
    id: BlockType.HARDENED_CLAY_CYAN,
    name: 'Cyan Clay',
    solid: true,
    transparent: false,
    textureIndex: 27,
  },
  [BlockType.HARDENED_CLAY_MAGENTA]: {
    id: BlockType.HARDENED_CLAY_MAGENTA,
    name: 'Magenta Clay',
    solid: true,
    transparent: false,
    textureIndex: 28,
  },
  [BlockType.HARDENED_CLAY_ORANGE]: {
    id: BlockType.HARDENED_CLAY_ORANGE,
    name: 'Orange Clay',
    solid: true,
    transparent: false,
    textureIndex: 29,
  },
  [BlockType.PAINTING_1]: {
    id: BlockType.PAINTING_1,
    name: 'Painting 1',
    solid: true,
    transparent: false,
    textureIndex: 30,
  },
  [BlockType.PAINTING_2]: {
    id: BlockType.PAINTING_2,
    name: 'Painting 2',
    solid: true,
    transparent: false,
    textureIndex: 31,
  },
};
